diff -Naur a/src/Makefile b/src/Makefile
--- a/src/Makefile	2020-01-04 20:17:28.927505961 +0000
+++ b/src/Makefile	2020-01-04 20:20:42.559096573 +0000
@@ -20,7 +20,7 @@
 RC_USER=$(shell whoami)
 RC_DATE=$(shell /bin/date)
 RC_BUILD_DATE=$(shell /bin/date +'%b %d %Y')
-PLATFORM=$(shell uname -i)
+PLATFORM=$(shell uname -m)
 
 EXTRA_CFLAGS += -D__LINUX__
 EXTRA_CFLAGS += -DRC_AHCI_SUPPORT -DRC_AMD_AHCI -DRC_AHCI_AUTOSENSE
