--- a/Makefile	2015-04-15 17:53:36.000000000 +0100
+++ b/Makefile	2015-04-15 21:08:22.000000000 +0100
@@ -1,4 +1,4 @@
-SBINDIR=/usr/local/sbin
+SBINDIR=/usr/sbin
 MANDIR=/usr/share/man/man8
 OBJDIR=obj
 
@@ -33,8 +33,8 @@
 		rm -rf $(OBJDIR)
 
 install: all
-		install -m 4755 iwleeprom $(SBINDIR)
-		install -m 644 iwleeprom.8.gz $(MANDIR)
+		install -m 0755 iwleeprom $(SBINDIR)
+		install -m 0644 iwleeprom.8.gz $(MANDIR)
 
 uninstall:
 		rm -f $(SBINDIR)/iwleeprom
